### ISSUE TITLE
Cannot parse config file

### ISSUE THREAD

**Issue by ooii** [lorenwest/node-config#221]
Hi,

I'm not able to parse the config file.
Here is its content:
```javascript
{
	"server": {
		"host": "localhost",
		"port": 8080
	},
	"mongodb": {
		"host": "192.168.99.100",
		"port": 32769
	}
}
```

And here is the code of the server:
```javascript
var config = require('config');
// variable setting the port
var serverConfig = config.get('server');
var port = serverConfig.port;        // set our port

var mongoConfig = config.get('mongodb');
var mongoose   = require('mongoose');
mongoose.connect('mongodb://'+mongoConfig.host+'/api:'+mongoConfig.port);
```
And each time I run `node server.js`, I have the following error:
```
/tmp/myServer/config/default.js:2
	"server": {
	        ^
Error: Cannot parse config file: '/tmp/myServer/config/default.js': SyntaxError: Unexpected token :
    at util.parseFile (/tmp/myServer/node_modules/config/lib/config.js:925:11)
    at /tmp/myServer/node_modules/config/lib/config.js:663:28
    at Array.forEach (native)
    at /tmp/myServer/node_modules/config/lib/config.js:659:14
    at Array.forEach (native)
    at util.loadFileConfigs (/tmp/myServer/node_modules/config/lib/config.js:658:13)
    at new Config (/tmp/myServer/node_modules/config/lib/config.js:119:27)
    at Object.<anonymous> (/tmp/myServer/node_modules/config/lib/config.js:1597:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```
If you have any idea, I'll be glad to hear it.
Thanks.

**Comment by markstos** [comment]
YOu named the file ".js", so it's attempted to be parsed as JavaScript, but the file appears that's trying to contain JSON instead.  I recommend the JavaScript format myself, in which case you need to something like:

```
module.exports = {
   // Put your JavaScript object here. 
};
```

This isn't a bug in a node-config, so I'm closing this issue.
