### ISSUE TITLE
Illegal invocation when I use process.stdout in a .js config file

### ISSUE THREAD

**Issue by thevtm** [lorenwest/node-config#301]
I'm trying to config `bunyan` but it throws `Illegal invocation` when I use `process.stdout` in a `.js` config file.

*config/default.js*
```javascript
module.exports = {
  logger: {
    name: 'app',
    streams: [{
      level: 'info',
      stream: process.stdout
    }, {
      level: 'debug',
      path: './logs/dev.log'
    }]
  }
}
```

*app.js*
```javascript
var logger = bunyan.createLogger(config.logger)
logger.info({foo: 1})
```

*error*
```
net.js:715
      return handle.writeUtf8String(req, data);
                    ^

TypeError: Illegal invocation
    at createWriteReq (net.js:715:21)
    at Socket._writeGeneric (net.js:679:11)
    at Socket._write (net.js:702:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Socket.Writable.write (_stream_writable.js:215:11)
    at Socket.write (net.js:628:40)
    at Logger._emit (~/app/node_modules/bunyan/lib/bunyan.js:938:22)
    at Logger.info (~/app/node_modules/bunyan/lib/bunyan.js:1037:24)
    at Object.<anonymous> (~/app/app.js:22:8)
Program node . exited with code 1
```

**Comment by thevtm** [comment]
I also tested using just the `process.stdout` and got this.


*config/default.js*
```javascript
module.exports = {
  out: process.stdout
}
```

*app.js*
```javascript
var config = require('config')
config.out.write('foo')
```

*error*
```
~/app/node_modules/config/lib/config.js:1527
  return (obj !== null) && (typeof obj === 'object') && !(Array.isArray(obj));
                                                                ^

RangeError: Maximum call stack size exceeded
    at Function.isArray (native)
    at util.isObject (~/app/node_modules/config/lib/config.js:1527:65)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1061:14)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
    at util.attachProtoDeep (~/app/node_modules/config/lib/config.js:1062:12)
Program node . exited with code 1
```

**Comment by lorenwest** [comment]
Configuration objects are designed to be POJOs defined in static configuration files. Complex configuration objects don't fit the profile if they can't be traversed, especially if they contain circular references as process.stdout apparently does.

**Comment by markstos** [comment]
I also use `node-config` and log to stdout. 

My workaround for this issue is simple: The logging to stdout is the default (for bunyan), so I don't specify it in the config file.
