### ISSUE TITLE
TypeError: Property description must be an object: undefined

### ISSUE THREAD

**Issue by kgoerlitz** [lorenwest/node-config#321]
With the latest version, 1.20.2, I get the following error when trying to use the util.extendDeep() function:

```
.../node_modules/config/lib/config.js:1420
        Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(Object(mergeFrom), prop));
               ^
TypeError: Property description must be an object: undefined
    at Function.defineProperty (native)
    at .../node_modules/config/lib/config.js:1420:16
    at Array.forEach (native)
    at util.extendDeep (.../node_modules/config/lib/config.js:1400:9)
```

This occurs when extending one config with another config on the 'get' function.
A simple fix would be to check if the Object.getOwnPropertyDescriptor() return value is not undefined before using it in the Object.defineProperty() call.

**Comment by kgoerlitz** [comment]
Pull request #322 submitted to fix this issue.
