### ISSUE TITLE
integer in custom-environment-variables.json causes error

### ISSUE THREAD

**Issue by emclab** [lorenwest/node-config#542]
Have confg@3.0.1 in my nodejs (10) project. The custom-environment-variables.json under /config is like this:

  {
      "jwtPrivateKey": "dPL6TsZZY36hWXMs",
      "jwt_token_expire_hours":"24"
  }

There are quote mark around 24. If the quote mark is removed:

  {
      "jwtPrivateKey": "dPL6TsZZY36hWXMs",
       "jwt_token_expire_hours": 24
  }

Then, there is error:

  C:\d\code\js\emps_backend\node_modules\config\lib\config.js:1194
          throw Error(msg);
          ^

  Error: Illegal key type for substitution map at : number
      at _substituteVars (C:\d\code\js\emps_backend\node_modules\config\lib\config.js:1194:15)
      at Config.util.substituteDeep (C:\d\code\js\emps_backend\node_modules\config\lib\config.js:1199:3)
      at C:\d\code\js\emps_backend\node_modules\config\lib\config.js:1219:43
      at Array.forEach (<anonymous>)
      at Config.util.getCustomEnvVars (C:\d\code\js\emps_backend\node_modules\config  \lib\config.js:1215:12)
      at Config.util.loadFileConfigs (C:\d\code\js\emps_backend\node_modules\config\lib\config.js:653:28)
      at new Config (C:\d\code\js\emps_backend\node_modules\config\lib\config.js:136:27)
      at Object.<anonymous> (C:\d\code\js\emps_backend\node_modules\config\lib\config.js:1643:31)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

It seems that the 24 was mistaken as key. Is it a bug?

**Comment by markstos** [comment]
I don't think so. Environment variables always come through as strings, as
documented in the official docs for process.env.

Assuming that you can use an integer for an environment variable is a
mistake.
