### ISSUE TITLE
Trying to load module into config and assign variables

### ISSUE THREAD

**Issue by reggi** [lorenwest/node-config#97]
I'm pretty sure I'm not allowed to load module into config and assign variables, it's causing this weird bug.

```
/Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:944
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3)
          ^
Error: Cannot parse config file: '/Users/thomas/Desktop/fluffy_bunnies/config/default.js': Error: Cannot find module 'config'
    at Config._parseFile (/Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:944:11)
    at /Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:715:25
    at Array.forEach (native)
    at /Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:711:14
    at Array.forEach (native)
    at Config._loadFileConfigs (/Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:710:13)
    at new Config (/Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:115:5)
    at Object.<anonymous> (/Users/thomas/Desktop/fluffy_bunnies/node_modules/config/lib/config.js:1398:64)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by Jeet007das** [comment]
I'm also facing the same issue!

**Comment by lonebots** [comment]
I am also having the same issue and now  I am using default.js file extension. Is there a way to solve this problem? The issue is solved when using default.json but, is there any way around to used config module to export configuration details from a javascript file.
